local util = require "util"

local pickersMap = {
  require("pickers.arecibo"),
  require("pickers.autocommands"),
  require("pickers.buffers"),
  require("pickers.colorscheme"),
  require("pickers.command_history"),
  require("pickers.commands"),

  { name = "current_buffer_tags", title = "", cmd = "", visible = false },
  { name = "fd", title = "", cmd = "", visible = false },
  { name = "file_browser", title = "", cmd = "", visible = false },
  { name = "filetypes", title = "", cmd = "", visible = false },
  { name = "find_files", title = "", cmd = "", visible = false },
  { name = "git_bcommits", title = "", cmd = "", visible = false },
  { name = "git_branches", title = "", cmd = "", visible = false },
  { name = "git_commits", title = "", cmd = "", visible = false },
  { name = "git_files", title = "", cmd = "", visible = false },
  { name = "git_stash", title = "", cmd = "", visible = false },
  { name = "git_status", title = "", cmd = "", visible = false },
  { name = "grep_string", title = "", cmd = "", visible = false },
  { name = "help_tags", title = "", cmd = "", visible = false },
  { name = "highlights", title = "", cmd = "", visible = false },
  { name = "jumplist", title = "", cmd = "", visible = false },
  { name = "keymaps", title = "", cmd = "", visible = false },
  { name = "live_grep", title = "", cmd = "", visible = false },
  { name = "loclist", title = "", cmd = "", visible = false },
  { name = "lsp_code_actions", title = "", cmd = "", visible = false },
  { name = "lsp_definitions", title = "", cmd = "", visible = false },
  { name = "lsp_document_diagnostics", title = "", cmd = "", visible = false },
  { name = "lsp_document_symbols", title = "", cmd = "", visible = false },
  { name = "lsp_dynamic_workspace_symbols", title = "", cmd = "", visible = false },
  { name = "lsp_implementations", title = "", cmd = "", visible = false },
  { name = "lsp_range_code_actions", title = "", cmd = "", visible = false },
  { name = "lsp_references", title = "", cmd = "", visible = false },
  { name = "lsp_type_definitions", title = "", cmd = "", visible = false },
  { name = "lsp_workspace_diagnostics", title = "", cmd = "", visible = false },
  { name = "lsp_workspace_symbols", title = "", cmd = "", visible = false },
  { name = "man_pages", title = "", cmd = "", visible = false },
  { name = "mapper", title = "", cmd = "", visible = false },
  { name = "marks", title = "", cmd = "", visible = false },
  { name = "oldfile", title = "", cmd = "", visible = false },
  { name = "pickers", title = "", cmd = "", visible = false },
  { name = "planets", title = "", cmd = "", visible = false },
  { name = "quickfix", title = "", cmd = "", visible = false },
  { name = "registers", title = "", cmd = "", visible = false },
  { name = "reloader", title = "", cmd = "", visible = false },
  { name = "resume", title = "", cmd = "", visible = false },
  { name = "search_history", title = "", cmd = "", visible = false },
  { name = "spell_suggest", title = "", cmd = "", visible = false },
  { name = "symbols", title = "", cmd = "", visible = false },
  { name = "tags", title = "", cmd = "", visible = false },
  { name = "tagstack", title = "", cmd = "", visible = false },
  { name = "treesitter", title = "", cmd = "", visible = false },
  { name = "vim_options", title = "", cmd = "", visible = false },
  { name = "YankHistoryPaste", title = "", cmd = "", visible = false },
}

return pickersMap
